### ISSUE TITLE
Cannot access the ACP after installing previous version.

### ISSUE THREAD

**Issue by niftysmith** [Sajaki/RecentTopics#100]
### Expected Behavior
Access to the ACP.

### Actual Behavior
`[phpBB Debug] PHP Warning: in file [ROOT]/phpbb/class_loader.php on line 160: require(./../ext/paybas/breadcrumbmenu/event/listener.php): failed to open stream: No such file or directory

Fatal error: require(): Failed opening required './../ext/paybas/breadcrumbmenu/event/listener.php' (include_path='.:/usr/lib/php7.1') in /homepages/10/d330051118/htdocs/clickandbuilds/phpBB/thornsuprising/phpbb/class_loader.php on line 160`

### Steps to Reproduce the Problem

  1. Installed Recent Topics v 2.2.6
  2. Deactivated and uninstalled Recent Topics v 2.2.6, deleting via FTP after Deactivation. Perhaps I forgot to clear my cache.
  3. Installed Recent Topics v 2.2.7
  4. Got error above.
  5. Deleted 2.2.7 via FTP. Reinstalled 2.2.6. Still have the error above.

### Specifications

  - phpbb version: 3.2.2
  - recenttopics version: 2.2.6 and then 2.2.7 ... I'm guessing it's 2.2.6 is where the error originated.

**Comment by Leinad4Mind** [comment]
The error appears because you've deleted probably too the breadcrumbmenu folder. And thats another extension.
