### ISSUE TITLE
Hi how to make external page ?

### ISSUE THREAD

**Issue by yemlihakorkmaz** [Sajaki/RecentTopics#102]
hi bro. 

i want external page show this recent topics. 

i want show 10 recent topics external php page how make ?

### Steps to Reproduce the Problem

  1.
  1.
  1.

### Specifications

  - phpbb version:
  - recenttopics version:

**Comment by avandenberghe** [comment]
as of 2.2.7 an external page is included.
go to http://yourforum/app.php/rt/
