### ISSUE TITLE
Milk Theme - Sidebar shows in Top

### ISSUE THREAD

**Issue by fullfrontaltrucker** [Sajaki/RecentTopics#105]
Have Milk theme and when setting Recent Topics config in extensions ACP panel, I set it to sidebar and the recent topics instead show in the Top. As if I selected for it to display in the Top.

Have tried using different Include's and snippits from the paybas template files but cannot include it.

  - phpbb version: 3.2.2
  - recenttopics version: 2.2.7

**Comment by avandenberghe** [comment]
hi, 
as I don't own a copy of the milk theme, please ask for support at https://themeforest.net/item/milk-multipurpose-responsive-phpbb-31-theme/16119149/support
