### ISSUE TITLE
Recent Topics not showing as Read when there is no unread topics

### ISSUE THREAD

**Issue by AstroObject** [Sajaki/RecentTopics#106]
### Expected Behavior
When a topic has been read and there is no more unread posts on a thread/topic, the Recent Posts should show as being read.

### Actual Behavior
When a topic has been read, the post still shows as being unread. However, when you enter the forum, the post shows as being read. Only on the Recent Topics section does it show as not being read.

### Steps to Reproduce the Problem

  1. Cleared Cache on web browser
  2. Cleared Forum Cache on ACP
  3. Tried other browsers, same issue
  4. Mobile also shows as topics has new reply only to find out there is no new reply. 
  5. Talked with Style Author, however, same issue appears on default style.
### Specifications

  - phpbb version: 3.2.2
  - recenttopics version: 2.2.7

**Comment by avandenberghe** [comment]
hi, 
there are 2 settings to consider 
1) acp -> recent topics -> show unread topics only -> set "on"
2) ucp -> board preferences -> display options -> "Only display unread topics in recent topics:"   -> set "on"
