### ISSUE TITLE
Display problem when making a POLL

### ISSUE THREAD

**Issue by Galixte** [Sajaki/RecentTopics#108]
Hi @Sajaki,

could you take a look to this issue: https://www.phpbb.com/customise/db/extension/recent_topics_2/support/topic/194066

An answer was shared here: https://www.phpbb.com/customise/db/extension/recent_topics_2/support/topic/194066?p=645376#p645376

**Comment by avandenberghe** [comment]
this should be fixed now.

**Comment by Galixte** [comment]
Thanks!
