### ISSUE TITLE
Problem with stylePBTech - Recenttopics is more in the middle as on the right side

### ISSUE THREAD

**Issue by BogusCurry** [Sajaki/RecentTopics#11]
Hello ;D
I use both (PBtech and Recenttopics) the last versions, so I have a problem that the recent topics is more in the middle as on the right side from index. I have make a screenshot, so you better seen the problem, I hope ;D
![bildschirmfoto_2016-12-11_13-27-36](https://cloud.githubusercontent.com/assets/614576/21080095/af1a8896-bfa6-11e6-82ff-5d2c68c64fdb.png)

I hope you can fix or you can me say, how I can fix self this problem ;D

Have a nice Day ;D
Bogus

**Comment by Galixte** [comment]
Hi @Sajaki,

could you take a look, please ?

**Comment by avandenberghe** [comment]
I can't reproduce this issue.
