### ISSUE TITLE
support for [ABD] Images from post

### ISSUE THREAD

**Issue by paymydc** [Sajaki/RecentTopics#111]
Hi Sajaki,
Your recent topic very usefully for forum. And can you add a support for [ABD] Images from post

[ABD] Images from posts can let your first image show on topic list.
If compatible with this extension recent topic will more completely.

Here is link [ABD] Images from posts 
https://www.phpbb.com/community/viewtopic.php?t=2274841

PAY YoY

**Comment by avandenberghe** [comment]
i think there is not enough space to insert an image in the recent topics listing.
