### ISSUE TITLE
Customize what is displayed or not

### ISSUE THREAD

**Issue by Herve-be** [Sajaki/RecentTopics#115]
### Expected Behavior
Display
    Topic title
    Topic Forum name
    **Last post author's pseudo**
    Last message date / time

### Actual Behavior
Displays
    Topic title
    Topic Forum name
    **Rating (1 to 10 stars)**
    Last message date / time

### Steps to Reproduce the Problem

No peculiar steps.

### Specifications

  - phpbb version: 3.2.8
  - recenttopics version: 2.2.7

**Comment by Galixte** [comment]
Hi @Sajaki,

could you take a look, please?

Regards.

**Comment by Herve-be** [comment]
Hi,

When the recent subjects are on top or below the forum I can see the userid (pseudo) of the last message of each recent subject.

Is it possible to see it when recent subjects is on the right as well ?

For instance

Rampe led Idéale cuve 150*50*65 <https://www.leforumrecifal.com/viewtopic.php?f=13&t=682>  

Techniques récifales <https://www.leforumrecifal.com/viewforum.php?f=8>  » Le matériel <https://www.leforumrecifal.com/viewforum.php?f=13>  

Dernier message 14 mars 2020 22:16

 

Reduce the date width (i.e. Last msg 14/03/2020 22:16) so that the userid can be located on the same line ?

 

Thanks a lot for your work

Rudy

 

De : Raphaël M. [mailto:notifications@github.com] 
Envoyé : jeudi 12 mars 2020 19:32
À : Sajaki/RecentTopics
Cc : Herve-be; Author
Objet : Re: [Sajaki/RecentTopics] Customize what is displayed or not (#115)

 

Hi @Sajaki <https://github.com/Sajaki> ,

could you take a look, please?

Regards.

**Comment by avandenberghe** [comment]
the feature suggestion is now implemented.

**Comment by Herve-be** [comment]
Many thanks !
Would it be possible to suppress the rating (the stars) also ?

**Comment by Galixte** [comment]
@Sajaki thanks for improving your tool.💪

@Herve-be,

The displaying of stars comes from Thanks for posts extension? https://www.phpbb.com/customise/db/extension/thanks_for_posts_2/

EDIT: OK, reported here: https://github.com/Sajaki/RecentTopics/issues/118.
