### ISSUE TITLE
Topiclink redirects to first post

### ISSUE THREAD

**Issue by cindyullmann** [Sajaki/RecentTopics#116]
### Expected Behavior
topiclink should redirect to newest post (the little arrow still does)

### Actual Behavior
it redirects to first post of the topic

### Steps to Reproduce the Problem

  1. enable extension
  2. click on a topic link (not the arrow next to date and time)

### Specifications

  - phpbb version: 3.3.0
  - recenttopics version: 2.2.8

**Comment by avandenberghe** [comment]
this is changed in v2.2.9

**Comment by avandenberghe** [comment]
this was reverted in 2.2.14. topiclink redirects to First post.
