### ISSUE TITLE
Suppress rating (the stars)

### ISSUE THREAD

**Issue by Herve-be** [Sajaki/RecentTopics#118]
### Expected Behavior
Display
Topic title
Topic Forum name
Last post author's pseudo <== i've asked to add this, it has been done, all right
Last message date / time

### Actual Behavior
Displays
Topic title
Topic Forum name
Rating (1 to 10 stars) <== at the same time I've asked to suppress this, it's still there
Last post author's pseudo
Last message date / time

### Steps to Reproduce the Problem

No special steps, concerns Recent topics on the right

### Specifications

  - phpbb version: 3.3.0
  - recenttopics version: 2.2.9

**Comment by avandenberghe** [comment]
hi, 
There is no rating functionality in RecentTopics. 
Are you running another extension ?

**Comment by Herve-be** [comment]
Hi,

I’m running « Thanks for posts » which is supposed to Add the ability to thank the author and to use per posts/topics/forum rating system based on the count of thanks.

https://www.phpbb.com/customise/db/extension/thanks_for_posts_2/

Example here under.

 

Do you think it can add rating to Recent Topics without your control ?

How to remove it ?

 

Rudy

 



 

De : Sajaki [mailto:notifications@github.com] 
Envoyé : lundi 16 mars 2020 13:58
À : Sajaki/RecentTopics
Cc : Herve-be; Author
Objet : Re: [Sajaki/RecentTopics] Suppress rating (the stars) (#118)

 

hi,
There is no rating functionality in RecentTopics.
Are you running another extension ?

**Comment by avandenberghe** [comment]
hello,

can you try this: 

open this file

`thanks_for_posts/styles/prosilver/template/event/topiclist_row_append.html`

```
{% if topicrow %}
    {% set rating = topicrow %}
{% elseif recent_topics %}
    {% set rating = recent_topics %}
{% endif %}
{% include 'topicrow_rating_body.html' %}

```
replace with 

```
{% if topicrow %}
    {% set rating = topicrow %}
{% endif %}
{% include 'topicrow_rating_body.html' %}
```

**Comment by Herve-be** [comment]
Yesssss !

hartelijk bedankt

 

As you can fix other people's extensions, may I abuse your kindness ?

Since I upgraded phpBB 3.2.8 to 3.3.0 the Kalender extension works fine except the “hide” button does not react anymore.

I’ve asked the author but he does not responds.

 

You can see an example here www.leforumrecifal.com

The button “Masquer les évènements aujourd’hui” should hide the calendar located just above that button.

Extensions download :  <http://calendar.zoo-am-ring.de/> http://calendar.zoo-am-ring.de/

 

If you have some time to lose …

Rudy

 

 

De : Sajaki [mailto:notifications@github.com] 
Envoyé : lundi 16 mars 2020 18:38
À : Sajaki/RecentTopics
Cc : Herve-be; Author
Objet : Re: [Sajaki/RecentTopics] Suppress rating (the stars) (#118)

 

hello,

can you try this:

open this file

thanks_for_posts/styles/prosilver/template/event/topiclist_row_append.html

{% if topicrow %}
    {% set rating = topicrow %}
{% elseif recent_topics %}
    {% set rating = recent_topics %}
{% endif %}
{% include 'topicrow_rating_body.html' %}
 

replace with

{% if topicrow %}
    {% set rating = topicrow %}
{% endif %}
{% include 'topicrow_rating_body.html' %}

**Comment by Galixte** [comment]
@Herve-be Please, you submit a new request which doesn’t concern this extension and at the same time it doesn’t concern your original request. This way makes the discussion confused and not benefit for visitors.  ;)

You should be patient. You have opened an issue here: https://www.phpbb.de/community/viewtopic.php?p=1402287#p1402287. Your question was answered here: https://www.phpbb.de/community/viewtopic.php?p=1402327#p1402327. And a fix is available here: https://www.phpbb.de/community/viewtopic.php?p=1401969#p1401969. Otherwise try this tool: https://www.phpbb.com/community/viewtopic.php?f=456&t=2469651.
