### ISSUE TITLE
Fetching last page doesnt work to enable "all" pages

### ISSUE THREAD

**Issue by bug-i** [Sajaki/RecentTopics#119]
Argh. Doesnt work in the latest release to fetch the last page

_Originally posted by @bug-i in https://github.com/Sajaki/RecentTopics/issues/67#issuecomment-600889344_

**Comment by Galixte** [comment]
Hi @Sajaki,

could you take a look, please?

Regards.

**Comment by bug-i** [comment]
To be honest, increasing from 100 to 1000 is nice but still not enough. If I see "all" in the option, I do expect to see "all", not 1000 paged. Dont know if my board is an exception there, but I do have 11k topics, therefore 1000 still isnt enough. No problem for me, as I now do know where to change the value, but still not consistend or at least irritating.

**Comment by avandenberghe** [comment]
i'm working on a better fix, that one was just something to get it out of the door.

**Comment by bug-i** [comment]
👍Perfect. Thanks
