### ISSUE TITLE
Sidebar doesn't work

### ISSUE THREAD

**Issue by LielR** [Sajaki/RecentTopics#121]
### Steps to Reproduce the Problem

  1. when I choose the side option it still shows the recent topics upon the page
  1.
  1.

### Specifications

  - phpbb version: 3.2.9 design MILKv2.
  - recenttopics version:

**Comment by avandenberghe** [comment]
UCP settings override ACP. 

can you check under user control panel -> board preferences -> Edit display options -> Select location.

**Comment by LielR** [comment]
No mate it doesn't work at all ;(

>

**Comment by LielR** [comment]
Well there is something weird.
I copy the forum files to another domain and it works there and in my one
it doesn't work.
can u help me to find why ?

>

**Comment by LielR** [comment]
Nevermind I find the issue.
I removed myself from the group 'Registered Users'.

>
