### ISSUE TITLE
page selector is alway on page1

### ISSUE THREAD

**Issue by bug-i** [Sajaki/RecentTopics#125]
### Expected Behavior
When I jump into page4 (example, could be any other page) then I expect that page4 is activated

### Actual Behavior
content of page4 is shown, but page selector jumps back to page1

  - phpbb version:
  - recenttopics version: 2.2.12

this happens on 2 of my forums. One with a very clean installation and almost no other extensions, so I think this is a bug of RecentTopics

**Comment by avandenberghe** [comment]
never seen this before..

**Comment by bug-i** [comment]
ah, just figured out that this is only happens, when "show all pages" is activated!
