### ISSUE TITLE
User Avatar not showing correctly 

### ISSUE THREAD

**Issue by Dode123** [Sajaki/RecentTopics#127]
### Expected Behavior
User avatars are displayed in the recent topic module. 

### Actual Behavior
They don't appear, just the default "man" avatar.

### Steps to Reproduce the Problem
N/A

### Specifications

  - phpbb version: 3.3
  - recenttopics version: 2.2.12

The user avatar is not showing up in the recent topic table. The avatars correctly show right below on the regular forum categories.
![Annotation 2020-05-04 113141](https://user-images.githubusercontent.com/31342092/80953129-3b55ae00-8dfb-11ea-9274-b52aebf63c52.jpg)

**Comment by Dode123** [comment]
Any update on this @Sajaki ? =)

**Comment by avandenberghe** [comment]
it's a new feature request.
