### ISSUE TITLE
Messed up layout from 2.1.2 under phpbb3.2 (rc2)

### ISSUE THREAD

**Issue by designer2k2** [Sajaki/RecentTopics#13]
Hello,

under 3.2rc2 the layout is not working, it looks like this:
![phpbb32rc2](https://cloud.githubusercontent.com/assets/1591573/21548433/9d6f5c12-cdec-11e6-97d7-5a234d4dca30.PNG)

where under 3.1.10 like this:
![phpbb31010](https://cloud.githubusercontent.com/assets/1591573/21548442/aa1e68e0-cdec-11e6-93c6-f6d3469ac8ea.PNG)

I hope you have 3.2 on your list...

**Comment by Sajaki** [comment]
hi, 
the code for 3.2 is in another branch. 
https://github.com/Sajaki/RecentTopics/tree/feature/32
i'm working on it.

**Comment by designer2k2** [comment]
great to hear that! 

looks a bit nicer:
![php32rc2_220rc1](https://cloud.githubusercontent.com/assets/1591573/21549373/1aa1fa8c-cdf2-11e6-8196-be642b43669a.PNG)

will wait for your release, thanks for your work!

**Comment by Sajaki** [comment]
it should be fixed now.

**Comment by designer2k2** [comment]
99% solved!    This is 2.2.0-RC2  on 3.2:
![unbenannt](https://cloud.githubusercontent.com/assets/1591573/21776497/3210a5c2-d69b-11e6-807d-133557b6ea34.PNG)

The "Aktuelle Themen" wraps...
