### ISSUE TITLE
Displays topic order incorrectly 

### ISSUE THREAD

**Issue by mrix2000** [Sajaki/RecentTopics#131]
When clicking on topic its expected to read the first post in the topic

After a upgrade to PHPBB3.3 the last post of the topic now displays when clicking on a topic in the recent topics list only.

### Specifications

  - phpbb version: PHPBB3.3
  - recenttopics version: 2.2.13

**Comment by avandenberghe** [comment]
This was changed to display the most newest post in the topic https://github.com/Sajaki/RecentTopics/issues/116 from release 2.2.9

**Comment by mrix2000** [comment]
Hello as explained this is no longer working in your latest version v2.2.13 (phpBB 3.2 / 3.3) ??????

**Comment by mrix2000** [comment]
> This was changed to display the most newest post in the topic #116 from release 2.2.9

Hello as explained in the prior message this is no longer working in your latest version v2.2.13 (phpBB 3.2 / 3.3) ?

Also please read your phpbb community pm as your Paypal link is not working in this mod, best regards
