### ISSUE TITLE
Wrong Post Order When Clicking on - Last post is shown instead of first.

### ISSUE THREAD

**Issue by mrix2000** [Sajaki/RecentTopics#132]
### Expected Behavior
When Clicking Topic Title the First post should be shown of the topic.

### Actual Behavior
When clicking on topic title on latest version v2.2.13 you first see the last post.

I can understand it was initually fixed in a prior version but its now happening again in v2.2.13 unless there is a newer version ?

### Specifications

  - phpbb version: PHPBB 3.3
  - recenttopics version: v2.2.13

**Comment by ncesar** [comment]
This is not really an issue, it is a user(your) prefference. The default behavior is to show the latest post.

See: https://wiki.phpbb.com/Forumrow_Template_Variables#forumrow.LAST_POST_SUBJECT
And if you wanna look into the file: `ext\paybas\recenttopics\styles\all\template` line 49

**Comment by mrix2000** [comment]
Hello this has never been the case in countless prior versions, only in this version.. when anyone clicks a topic in a recent topic list many will not only want to read the latest last post in that topic. Is there a simply way of changing this around ?

**Comment by ncesar** [comment]
My mistake then, sorry, I have not used this extension before(started today). If nobody answers your question until night(in my time), I will take a look and help you.

**Comment by mrix2000** [comment]
This has been a brilliant extension and such a huge positive to my forum, for many years its been working brilliantly, I have actually had to go back to using a version 2.2.7 for phpbb 3.2 which works as it always used to but it has issues with topic icons not displaying correctly while using phpbb 3.3.
If you have the know how to resolve this specific issue it would be hugely appreciated and very kind of you.

**Comment by avandenberghe** [comment]
There are different opinions on this. either options are possible (first or newest post in topic). the best way to handle this is to add a setting in ACP.

**Comment by mrix2000** [comment]
A setting in ACP would be perfect, if there is a quick file edit for the time being it would be appreciated.
Thank you

**Comment by ncesar** [comment]
Hi, I did not have time to test yesterday but looking in the wiki, you can change `LAST_POST_SUBJECT` to `POST_SUBJECT`.
see: https://wiki.phpbb.com/Viewtopic_Template_Variables#postrow.POST_SUBJECT

Go to `ext\paybas\recenttopics\styles\all\template` and choose the style that you are using(e.g: top, bottom, etc). Then, go to line 49 and change what I said above.

Let me know if this works so I can create a PR and to submit a dropdown menu in the ACP so users can change it.

**Comment by mrix2000** [comment]
Hello and thanks for your efforts, I have just tried and it removed the title of the topic completely.

The line of text I get at 49 is this....

`</a> {% endif %}<a href="{{ recent_topics.U_LAST_POST }}" class="topictitle">{{ recent_topics.LAST_POST_SUBJECT }}</a>`

**Comment by avandenberghe** [comment]
This was changed since 2.2.9. the default behaviour is to show the newest post.

https://github.com/Sajaki/RecentTopics/issues/116

> Hello this has never been the case in countless prior versions, only in this version.. when anyone clicks a topic in a recent topic list many will not only want to read the latest last post in that topic. Is there a simply way of changing this around ?

**Comment by mrix2000** [comment]
I know that is meant to be the case but its not, i have seen the same now on three seperate forums

**Comment by ncesar** [comment]
@mrix2000 if you still want this behavior, just change the line you've sent to me to:
						`<a href="{{ recent_topics.U_VIEW_TOPIC }}" class="topictitle">{{ recent_topics.TOPIC_TITLE }}</a>`

**Comment by mrix2000** [comment]
> @mrix2000 if you still want this behavior, just change the line you've sent to me to:
> `<a href="{{ recent_topics.U_VIEW_TOPIC }}" class="topictitle">{{ recent_topics.TOPIC_TITLE }}</a>`

Brilliant that done the trick! thanks for your time on this, mrix
