### ISSUE TITLE
ACP Tosses error on non-HTTPS hosts like local 

### ISSUE THREAD

**Issue by rmcgirr83** [Sajaki/RecentTopics#136]
Nothing more needs to be said

**Comment by avandenberghe** [comment]
Can't reproduce.

**Comment by rmcgirr83** [comment]
https://github.com/Sajaki/RecentTopics/blob/develop32/acp/recenttopics_module.php#L232
![Capture](https://user-images.githubusercontent.com/179079/88729565-d5c34600-d0f9-11ea-82ff-0734b1337fbf.PNG)
