### ISSUE TITLE
Call to undefined function

### ISSUE THREAD

**Issue by rmcgirr83** [Sajaki/RecentTopics#138]
`www.forum.com/app.php/rt`

A Picture is worth 1000 words
![Capture](https://user-images.githubusercontent.com/179079/91648164-c05b7780-ea29-11ea-9f97-3b3590175912.PNG)

**Comment by rmcgirr83** [comment]
https://github.com/Sajaki/RecentTopics/blob/develop32/core/recenttopics.php#L676

Need to add before

`				if (!function_exists('topic_status'))
				{
					include($this->root_path . 'includes/functions_display.' . $this->phpEx);
				}
`

**Comment by Dark1z** [comment]
Kind of done here : https://github.com/Sajaki/RecentTopics/pull/140

Best regards 👍

**Comment by rmcgirr83** [comment]
..and on that note, closed :)

**Comment by avandenberghe** [comment]
Fixed in 3.0.0: added guarded include of functions_display.php in display_recent_topics() so topic_status() is available on the standalone /app.php/rt page.

**Comment by avandenberghe** [comment]
Fix commit: 9552cc7
