### ISSUE TITLE
2.2.0-RC2 I change the permissions of the visitors 

### ISSUE THREAD

**Issue by borgesjoaquim** [Sajaki/RecentTopics#17]
I change the permissions of the visitors to not see the recent topics
And in the real they always come with the without permission

![guest](https://cloud.githubusercontent.com/assets/4094237/22045601/1ecba984-dd13-11e6-8e16-bc2742fd7dd8.JPG)
![giest](https://cloud.githubusercontent.com/assets/4094237/22045604/250c0ec4-dd13-11e6-834a-e70c54c0ba06.JPG)

**Comment by Sajaki** [comment]
fixed in 28fe3609f7936b88dbfb75cf1df0b67b2328dd03
