### ISSUE TITLE
Make topic icons clickable

### ISSUE THREAD

**Issue by Sajaki** [Sajaki/RecentTopics#19]
Now they are just images

**Comment by Sajaki** [comment]
they are already clickable, but only when the topic is unread. this is phpbb default behaviour.

**Comment by ffoknissom** [comment]
Sorry but unlike default PHPBB behaviour, the UNread topic icons are NOT clickable!

**Comment by ffoknissom** [comment]
Finaly solved 

https://github.com/Sajaki/RecentTopics/pull/72
