### ISSUE TITLE
Extention recenttopics 2..1.2.

### ISSUE THREAD

**Issue by chantal1002** [Sajaki/RecentTopics#22]
Bonjour,

J'ai rajouté le bloc "recents topics 2.1.2." mais je souhaiterais faire apparaitre sur une seule ligne
(sujet + nom du posteur du dernier post + date dans un bloc plus court)

Merci

Chantal

**Comment by Sajaki** [comment]
Bonjour Chantal,
C'est bien possible mais cela demande un peu de maipulation du fichier ext/paybas/recenttopics/styles/all/template/recent_topics_body.html
je vais voir ce que je ppuis faire.

**Comment by chantal1002** [comment]
ok merci beaucoup
J'attends votre retour :-)

**Comment by Galixte** [comment]
Salut Chantal,

à la lecture de ta demande je suppose que je n’ai plus à travailler dessus, bonne continuation.

**Comment by chantal1002** [comment]
Bonjour Galixte,

J'ai effectivement toqué à plusieurs portes (j'espère que tu avais vu mon message)

[quote="chantal"]
[quote="galixte"]http://www.ezcom-fr.com/viewtopic.php?p=3088#p3088[/quote]

J'ai vu merci beaucoup  :) 
par contre penses-tu qu'il soit possible de faire qqchose pour la suite de ma demande?
Je suis un peu ennuyée car ma demande se retrouve postée en plusieurs endroits..
J'ai vu ta réponse sur phpBB sur la faq de l'extension, j'ai fait la même demande sur le support concerné
J'espère arriver à mes fins entre vous tous  :) 
Merci
Chantal[/quote]

**Comment by chantal1002** [comment]
Bonjour, 
Ma demande est - elle réalisable? 
Merci
Chantal

**Comment by chantal1002** [comment]
Bonjour,

Sans réponse je me permets de renouveler ma demande... avez-vous du nouveau?
Merci de votre réponse
Chantal
