### ISSUE TITLE
Style error on template we_clearblue

### ISSUE THREAD

**Issue by mvldebian** [Sajaki/RecentTopics#23]
Icons do not work in the old version after migrating from 3.1.9 to 3.2
When applying new version of the plugin the layout is not correct

Running PhpBB 3.2 with old version 2.0.5 
![runnig with old plugin](https://cloud.githubusercontent.com/assets/25337130/22277658/196733a8-e29c-11e6-818b-b080950df793.PNG)

Running PhpBB 3.2 with NEW version
![running 3 2](https://cloud.githubusercontent.com/assets/25337130/22277553/3f1aaafe-e29b-11e6-8a14-00c523ea4169.PNG)

File for the we_clearblue theme that I use:

[recent_topics_body.zip](https://github.com/Sajaki/RecentTopics/files/728629/recent_topics_body.zip)

**Comment by Galixte** [comment]
Hi,

maybe you can adapt you style file with this https://github.com/PayBas/RecentTopics/blob/master/styles/we_universal/template/recent_topics_body.html as model.

**Comment by Kewee** [comment]
Hello !

you may use the file here : 
[we_clearblue.zip](https://github.com/Sajaki/RecentTopics/files/1199424/we_clearblue.zip)

I've changed the html's file. Put it in the folder recenttopic/styles next to the files "prosilver" and "all"

**Comment by avandenberghe** [comment]
works with https://github.com/bpiec/we_clearblue
