### ISSUE TITLE
Can't get recent topics to show

### ISSUE THREAD

**Issue by mLgz0rn** [Sajaki/RecentTopics#24]
For some reason I cannot get recent topics to show.
i'm using a custom theme, and guess that might be the issue.
this is the theme https://www.phpbb.com/community/viewtopic.php?f=476&p=14172361
download link is here https://www.lordcraft.net/files/file/350-legion-world-of-warcraft-phpbb3-forum-style/

and my forum page is http://nm-inc.clanroyal.dk/forums/
any help would be really appreciated

**Comment by Galixte** [comment]
This style was abandonned by his author, so…

**Comment by avandenberghe** [comment]
If you could produce a working link to the style, we could do it.

**Comment by Galixte** [comment]
@Sajaki [Legion v2.0.0 phpBB 3.1.9.zip](https://github.com/Sajaki/RecentTopics/files/1291080/Legion.v2.0.0.phpBB.3.1.9.zip)
