### ISSUE TITLE
Styles problem

### ISSUE THREAD

**Issue by lterlecki** [Sajaki/RecentTopics#25]
phpBB: 3.2.0
Recent Topics: 2.1.3
Installed styles:
- prosilver￼
- Absolution
- ne-blackgreen
- prosilver Special Edition
- SE Square
- SE Square Left

For all styles view of extention looks like:
![recent topics](https://cloud.githubusercontent.com/assets/22658233/22638512/dad4f4e8-ec48-11e6-97dc-5a14fc00c52b.jpg)

**Comment by Sajaki** [comment]
release 2.1.3 is not designed for phpbb 3.2.0, please use 2.2
