### ISSUE TITLE
Sidebar goes to top after admin login

### ISSUE THREAD

**Issue by rneal9080** [Sajaki/RecentTopics#28]
Hello!

I recently updated to Recent Topics for 3.2, and was able to get everything working correctly.  I was able to set the Recent Topics to the side, just as intended. However, when only an admin logs in, the recent topics moves up to the top. For all other users, it stays put logged in and out. Both admins for the site experienced this and we're on different sides of the globe, as well as happening in firefox and chrome. Cache was cleared multiple times. 

Obviously I can ignore this since it doesn't affect most users, but I would love to see what they're seeing while logged in. Thanks so much and thank you for updating recent topics so quickly!

**Comment by Sajaki** [comment]
hi, this is because the admins can overrule the default settings. admins should be able to go to the user control panel and change the position of the recent topics block.

**Comment by rneal9080** [comment]
I would have never thought to look there. Thank you so much!
