### ISSUE TITLE
Explanation for new paging limit option isn’t correct

### ISSUE THREAD

**Issue by Galixte** [Sajaki/RecentTopics#37]
Hi @Sajaki,

your new paging limit option added here: https://github.com/Sajaki/RecentTopics/commit/d687f938a0030bb0f343d06214a54f42bbb6f74b#diff-cb09c805420e96ca1bd092f395b93ff9it lacks explanations.

I mean, if i check this option: https://github.com/Sajaki/RecentTopics/blob/d687f938a0030bb0f343d06214a54f42bbb6f74b/language/en/info_acp_recenttopics.php#L50 it will disable the displaying of the full “recent topics pagination” regardless of the new option “paging limit”. Users may be confused with the method to apply.

So, for those language keys:
https://github.com/Sajaki/RecentTopics/blob/d687f938a0030bb0f343d06214a54f42bbb6f74b/language/en/info_acp_recenttopics.php#L50
It should be:
```
	'RT_PAGE_NUMBER'                => 'Full displaying of recent topics pages',
	'RT_PAGE_NUMBER_EXP'            => 'Check to disable the full displaying of the recent topics pagination. If activated, all topics of the board will be paginated with all necessary pages (not recommended). If disabled, fill a number of pages to display in the option “Maximum number of pages”.',
```
instead of:
```
	'RT_PAGE_NUMBER'                => 'Recent topics pages',
	'RT_PAGE_NUMBER_EXP'            => 'Check to disable recent topics pagination.',
```

And for this language keys: https://github.com/Sajaki/RecentTopics/blob/d687f938a0030bb0f343d06214a54f42bbb6f74b/language/en/info_acp_recenttopics.php#L60 it should be:

```
	'RT_PAGE_NUMBERMAX'		=> 'Maximum number of pages',
	'RT_PAGE_NUMBERMAX_EXP'		=> 'Set the page maximum (1-999) to display in the recent topics pagination where the option “Full displaying of recent topics pages” is disabled.',
```
instead of:
```
	'RT_PAGE_NUMBERMAX'		=> 'Maximum number of pages',
	'RT_PAGE_NUMBERMAX_EXP'		=> 'Set the page maximum (1-999)',
```
I will update the FRENCH translation too.

**Comment by Galixte** [comment]
Fixed in https://github.com/Sajaki/RecentTopics/pull/38 & https://github.com/Sajaki/RecentTopics/pull/39.

**Comment by avandenberghe** [comment]
the descriptions should now be clearer.
