### ISSUE TITLE
PAGINATION FEATURE: Limit the “Click to jump to page…” button action

### ISSUE THREAD

**Issue by Galixte** [Sajaki/RecentTopics#40]
Hi @Sajaki,

on the index page, when de recent topics are displayed with pagination, for example, if:
- i set the value ```5``` for the maximum number of pages in the pagination,
- if i click on “Click to jump to page…” button,
- if i fill the value ```10```,
- if i click on “GO” button,
- ===> the Recent Topics table disappear.

I think the “Click to jump to page…” should be limited by the value of the maximum number of pages displayed in the pagination.

**Comment by Galixte** [comment]
An other linked issue, currently the “Click to jump to page…” functionnality disappears if the “Maximum number of pages :” option is set with a value less than 7 (1 to 6).

**Comment by avandenberghe** [comment]
This week it's hard to look at this extension as i'm finalising pbwow styles..

**Comment by Galixte** [comment]
I’m only report all findings about this.

This issue is minor and will still here as long as you wish. ;)

**Comment by Galixte** [comment]
A related styling issue: https://github.com/Sajaki/RecentTopics/issues/50#issuecomment-327751520.
