### ISSUE TITLE
checkmark page navigation doesnt work

### ISSUE THREAD

**Issue by bug-i** [Sajaki/RecentTopics#42]
In my installation (phpbb 3.2, recent topics 2.2.1) does the checkmark "page navigation" not work. No matter if I have the checkmark or not, the pagenavigation is displayed. 
Also the German translation is not correct:

"Seitenanzahl „Aktuelle Themen“:
Du kannst weitere aktuelle Themen mit einer kleinen Seitennavigation anzeigen lassen. **Um das Feature zu deaktivieren einfach „0“ eintragen.**"

To disable the feature enter "0" doesnt make sense with a checkmark :)

**Comment by Galixte** [comment]
Hi,

if you check the option “Full displaying of recent topics pages” the FULL pagination will be disabled and you will have to enter a number of pages in the next option: “Maximum number of pages”.

See this: https://github.com/Sajaki/RecentTopics/issues/37

You can submit a new PR for German translation. ;)

**Comment by bug-i** [comment]
Nope, that doesnt work here. The navigation is shown no matter if I have checked and unchecked the box.

![grafik](https://user-images.githubusercontent.com/29623218/27431999-bcda7cee-574e-11e7-8bb6-133a89d531ab.png)

**Comment by Galixte** [comment]
Hi @bug-i,

unchecked = all necessary pages (corresponding of the entire topics of the board) will be displayed in the pagination.
checked + “Maximum number of pages” option setted with a number = a number of pages will be displayed in the pagination (corresponding of the number setted for the ““Maximum number of pages” option).

Do you use the last version? On the last release, there is the option: “Maximum number of pages” with which you can set a number as limit of pages displayed in the pagination.

**Comment by bug-i** [comment]
yes I am using the latest version, but the number of pages is the same (1754) no matter I checked or unchecked the option :(

**Comment by Galixte** [comment]
Strange i don’t encounter this behaviour. @Sajaki What are the prerequisites to see that issue?

**Comment by Galixte** [comment]
@bug-i could you check if you didn’t use the appropriated version? See this: https://github.com/Sajaki/RecentTopics/issues/50#issuecomment-327638078.

**Comment by bug-i** [comment]
I just installed the mentioned version. Now the setting of a maximum page-number ist working perfect, but meanwhile I get used to the unlimited displaying of pages. 

I cant find an option now to disable the maximum page number -> (usually I would expect that a "0" disables the max page settings, but it doesnt.

**Comment by Galixte** [comment]
It’s already explained to disable the maximum page number: https://github.com/Sajaki/RecentTopics/issues/50#issuecomment-327638078 : Uncheck this setting “Full displaying of recent topics pages” you will activate the full pagination, and the maximum page number will be disabled.

**Comment by bug-i** [comment]
ah, ok - now I've got it. I was confused by the german translation of this option  
Seitenanzahl „Aktuelle Themen“:
Du kannst weitere aktuelle Themen mit einer kleinen Seitennavigation anzeigen lassen. Um das Feature zu deaktivieren einfach „0“ eintragen.

It (translated back into English) currently says 
"Number of "Recent Topics": You can enable a small site navigation. To disable this feature fill in "0".

So please update the German translation to: "Vollständige Anzeige aktueller Themen. Durch Deaktivieren dieser Option kann in der nachfolgenden Einstellung eine maximale Seitenanzahl angegeben werden"

Also there is no German translation for "Maximum number of pages:"

All in all I recommend that it would be easier to have only one option and if you fill in "0" that all topics are displayed.
