### ISSUE TITLE
Compatibility with extension collapsable categories

### ISSUE THREAD

**Issue by bug-i** [Sajaki/RecentTopics#43]
As mentioned here - could you please check if its possible that recent topics is compatible with collapsable categories? Thanks
https://www.phpbb.com/customise/db/extension/collapsible_forum_categories/support/topic/154806

**Comment by Galixte** [comment]
It’s not make sense to use this functionnality with Recent Topics because Rencent Topics was created to have a short list of new messages on the board to avoid browsing all forums.

Hide Recent topics means that this tool is useless.

**Comment by bug-i** [comment]
No, that doesnt mean that. With compatibility to the collapsing extension every user can decide if he wants to use/see it, or not, instead of globally switching it on (especially on the index page) for all users

**Comment by Galixte** [comment]
Hi @bug-i,

in “User Control Panel” => “Board preferences” => “Edit display options” => “Display recent topics :” option, each user can activate or disable the display of this extension.

**Comment by bug-i** [comment]
I know what you mean. But its a difference to do it with one simple click and collapse/expand whenever you like, to have an easier view on different topics and go to the admin panel and change the settings. Technically the feature is already there - as you have described it, but its not very comfy to use it.

**Comment by raykai** [comment]
im in need of this too.  it would be a good way to just collapse the recent Topics list. when we don't need it or just to free some screen space.

its the only reason I'm staying with the extension Top Stats from: [http://www.dmzx-web.net/viewtopic.php?f=66&t=2370](http://www.dmzx-web.net/viewtopic.php?f=66&t=2370)

as that one works with collapsible categories extension.  I would like to switch to your extension as the other one has many additions that i don't need like statistique.

**Comment by Galixte** [comment]
So, you prefer to hide the displaying of this functionality rather to disable it displaying from UCP? This will result by a page charging more slowly than a page without this feature activated.  It's a non-sense… or laziness request.

You can disable this in your UCP (User control panel) you’ll have two advantages:
- first, the page will be charged more efficient (light weight),
- 2nd, the functionality won’t be displayed as you want.

**Comment by raykai** [comment]
it's a user preference... all my other mods that show on index page has support for the collapsable categories mod ... the only one i just that doesn't is this one.. looks wired that all other boxes has a collapsible option but not the RecentTopics box. let's say its a lot faster to click on the collapsable button then always going in the UCP every time to switch it on off.

let's say its useful when you have a long forum.

Anyways thx for the mod.

**Comment by avandenberghe** [comment]
This is on the to-do list for v2.2.6. However, it wasn't on my radar before because recent topics when used with pbWoW already has a collapsable forum structure. therefore this feature will be for prosilver and its derivates only.
