### ISSUE TITLE
Compatibility with Topic Descriptions

### ISSUE THREAD

**Issue by bissim** [Sajaki/RecentTopics#44]
Would you mind to consider compatiblity with [Topic Descriptions](https://www.phpbb.com/community/viewtopic.php?f=536&t=2383701) extension ([here](https://github.com/rmcgirr83/topicdescription) is the GitHub repo)?

**Comment by jan-2017** [comment]
that would be awesome

**Comment by Galixte** [comment]
Hi @Sajaki,

could you take a look, please?

**Comment by avandenberghe** [comment]
Recent topics is compatible with extension "phpbb/topicprefixes". please use the most recent RT version. 
![rtview](https://user-images.githubusercontent.com/226730/44167290-b0cc9880-a0c5-11e8-8e39-f2b41f215d08.png)
