### ISSUE TITLE
Still show placeholder if no topic is available

### ISSUE THREAD

**Issue by bissim** [Sajaki/RecentTopics#45]
This option would be particularly meaningful if the option '_Only display unread topics in recent topics_' is enabled.
If users read all active topics available, **the Recent Topics block should not hide but show a placeholder instead** warning the user that there are currently no more topic available to read.

Here I attach some mock-up about the feature; don't mind the styling, I made it on the fly.
![cattura_2228](https://user-images.githubusercontent.com/9421424/27768698-1dae577a-5f1a-11e7-88e8-494377b9bd9e.PNG)

**Comment by avandenberghe** [comment]
hi, this is now available.
