### ISSUE TITLE
error in PostgreSQL installation

### ISSUE THREAD

**Issue by hubaishan** [Sajaki/RecentTopics#47]
in phpBB 3.2.1, recentTopics 2.2.1, postgrsql 9.4-9.6
I have this error after activation:
`
SQL ERROR [ postgres ]

ERROR: function from_unixtime(integer) does not exist LINE 1: ...on_id, tt.mark_time, ft.mark_time as f_mark_time, FROM_UNIXT... ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts. []

SQL

SELECT t.forum_id, t.topic_id, t.topic_type, t.icon_id, tt.mark_time, ft.mark_time as f_mark_time, FROM_UNIXTIME(t.topic_last_post_time) as sortcr FROM phpbb_topics t LEFT JOIN phpbb_topics_track tt ON (tt.topic_id = t.topic_id AND tt.user_id = 2) LEFT JOIN phpbb_forums_track ft ON (ft.forum_id = t.forum_id AND ft.user_id = 2) WHERE t.topic_id <> '0' AND t.topic_status <> 2 AND (t.forum_id IN ('3', '1', '6', '7', '8', '2', '5')) ORDER BY t.topic_last_post_time DESC LIMIT ALL OFFSET 0

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 999
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/postgres.php
LINE: 194
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/postgres.php
LINE: 258
CALL: phpbb\db\driver\postgres->sql_query()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 270
CALL: phpbb\db\driver\postgres->_sql_query_limit()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 321
CALL: phpbb\db\driver\driver->sql_query_limit()

FILE: [ROOT]/ext/paybas/recenttopics/core/recenttopics.php
LINE: 697
CALL: phpbb\db\driver\factory->sql_query_limit()

FILE: [ROOT]/ext/paybas/recenttopics/core/recenttopics.php
LINE: 242
CALL: paybas\recenttopics\core\recenttopics->gettopiclist()

FILE: [ROOT]/ext/paybas/recenttopics/event/listener.php
LINE: 88
CALL: paybas\recenttopics\core\recenttopics->display_recent_topics()

FILE: (not given by php)
LINE: (not given by php)
CALL: paybas\recenttopics\event\listener->display_rt()

FILE: [ROOT]/vendor/symfony/event-dispatcher/EventDispatcher.php
LINE: 184
CALL: call_user_func()

FILE: [ROOT]/vendor/symfony/event-dispatcher/EventDispatcher.php
LINE: 46
CALL: Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()

FILE: [ROOT]/phpbb/event/dispatcher.php
LINE: 60
CALL: Symfony\Component\EventDispatcher\EventDispatcher->dispatch()

FILE: [ROOT]/phpbb/event/dispatcher.php
LINE: 46
CALL: phpbb\event\dispatcher->dispatch()

FILE: [ROOT]/index.php
LINE: 235
CALL: phpbb\event\dispatcher->trigger_event()
`

**Comment by Galixte** [comment]
Hi @Sajaki could you take a look, please?
