### ISSUE TITLE
No way to limit number of pages ?

### ISSUE THREAD

**Issue by exxosuk** [Sajaki/RecentTopics#50]
I'm up to 36 pages so far on my new forum. Using phpbb 3.2.1 with RT 2.2.1..

I've not used RT before, but have seen it in action on other forums and limited to 5 pages... There seems to be no option for this ? But by what others have said, it used to be in older RT versions ?

**Comment by Galixte** [comment]
Hi @exxosuk,

do you use the last snapshot here: ? It seems like this: https://github.com/Sajaki/RecentTopics/issues/42.

I explained here: https://github.com/Sajaki/RecentTopics/issues/37. From my side it’s fixed, you can set the number of pages in pagination from Recent topic block.

You have to disable the “Full displaying of recent topics pages” option (check this). Then, you define the number of pages you want to display with the option “Maximum number of pages”. ;)

**Comment by exxosuk** [comment]
Thanks for reply. I used the latest download from here yesterday. 

Can you confirm these are all the options listed that there are supposed to be ?  Or are there some other options somewhere you are referring to ?

![capture](https://user-images.githubusercontent.com/22227683/30134231-4d34e064-934e-11e7-889a-71d1ae0f355b.JPG)

**Comment by Galixte** [comment]
Except these, you have some of these in UCP (the same as in ACP for location, sort by and only display…) and user permissions, that’s all.

You don’t have disabled the full pagination in your screenshot (“Recent topics pages”), so all the pages will be displayed in pagination. 

I think about the english language from you screenshot, i update this on 19 june 2017, you don’t use the last snapshot.

For phpBB 3.2.x, you have to use this. https://github.com/Sajaki/RecentTopics/archive/develop32.zip.
For phpBB 3.1.x: use this: https://github.com/Sajaki/RecentTopics/archive/master.zip.

When you will update the extension, you will have a new option to fill the number of pages to display in pagination.
1./ By checking this setting “Full displaying of recent topics pages” you will disable the full pagination,
 2./ Then, fill the value 5 for the option: “Maximum number of pages” to display 5 pages in pagination.

Thanks for reporting!

**Comment by exxosuk** [comment]
I tried the develop32 one, just those files and it wasn't seen in the extension list. So I installed 2.2.1 again, and copied the files over the top, enabled the extension again, still says 2.2.1 and nothing has changed anyway. 

![capture](https://user-images.githubusercontent.com/22227683/30155431-b997db92-93b4-11e7-9383-0cc2aee6ea06.JPG)

**Comment by exxosuk** [comment]
oh, no, there is a new option there now! My bad..

![capture](https://user-images.githubusercontent.com/22227683/30155616-35375c6e-93b5-11e7-9fc5-df25f9487516.JPG)


![2](https://user-images.githubusercontent.com/22227683/30155665-4fa7f6f8-93b5-11e7-83d8-53549363d305.JPG)

Probably the version number confused me a little here.. Though it seems to be all fixed now, great work, and thanks for keeping this great extension updated!

**Comment by exxosuk** [comment]
I did noticed the page boxes appear at the bottom of the recent topics area now ?  I could be blind and not noticed it before, but sure it didn't do that before ?  Maybe a feature request to turn that off ?

![capture](https://user-images.githubusercontent.com/22227683/30157515-6b8c66ec-93ba-11e7-8bf7-2ffe3c0fb1ab.JPG)

**Comment by Galixte** [comment]
Yes it will be fixed in a new release i guess, see here for report about pagination feature: https://github.com/Sajaki/RecentTopics/issues/40.
