### ISSUE TITLE
Update languages

### ISSUE THREAD

**Issue by avandenberghe** [Sajaki/RecentTopics#51]
before releasing 2.2.2, all languages should be reviewed as the english version changed considerably.

**Comment by Galixte** [comment]
Thanks for this beautiful update! It’s done from my side. ;)

**Comment by avandenberghe** [comment]
done
- English
- French
- Dutch 
- German

to do 
- ar, cs, da, es, es_x_tu, it, pt, ru, sv

**Comment by Galixte** [comment]
@alhitary @R3gi @Spirit55555 @jensz12 @Flerex @Mauron @rxu, please.

**Comment by Flerex** [comment]
Which is the commit with the English changes? I need it in order to review the Spanish translation and I can't seem to find it.

**Comment by avandenberghe** [comment]
it's this one. https://github.com/Sajaki/RecentTopics/commit/20ac97dd2efe44fb671d0bfc29d2556cd1748832#diff-cb09c805420e96ca1bd092f395b93ff9

**Comment by Flerex** [comment]
I just checked the Spanish translations `es` and `es_x_tu` and both of them have the new translations. The only one that didn't have them was `es`, but I already added them in [this](https://github.com/Sajaki/RecentTopics/pull/49) pull request.

**Comment by R3gi** [comment]
@Galixte @Sajaki 
Hi, Czech translation update is here: https://github.com/Sajaki/RecentTopics/pull/58
I hope it's all right.

**Comment by Galixte** [comment]
@Flerex i’m sorry i didn’t check before call you, my bad.

Thanks @R3gi!

**Comment by Galixte** [comment]
@Flerex i’m sorry but for ```es_x_tu``` it’s not up to date: see this: https://github.com/Sajaki/RecentTopics/tree/20ac97dd2efe44fb671d0bfc29d2556cd1748832/language/es-x-tu (last update from this language): Snapshot from 10 september at 19h06.

After that, @Sajaki just renamed the folder https://github.com/Sajaki/RecentTopics/commits/develop32/language/es_x_tu, so the files aren’t up to date. Snapshot from 10 september at 19h10.

**Comment by Flerex** [comment]
@Galixte yeah, you are right. I didn't see the new lines at the bottom.

I've added the new translations in both the `es` and `es_x_tu` language packs, along with some very healthy changes in this [pull request](https://github.com/Sajaki/RecentTopics/pull/61).

**Comment by avandenberghe** [comment]
Thanks all very much for the translations 🍺 👍 :-)
