### ISSUE TITLE
rt_unreadonly is still presents in database after full uninstall

### ISSUE THREAD

**Issue by Galixte** [Sajaki/RecentTopics#53]
Hi @Sajaki,

i tryed uninstalling, it works fine, but there is a config value still presents in the database: ```rt_unreadonly```:
![2017-09-11 05_44_16-localhost_8080 _ localhost _ qi_phpbb321 _ phpmyadmin 4 5 4 1 - opera](https://user-images.githubusercontent.com/7478287/30257769-94ec8010-96b4-11e7-8fb3-4ff061de804e.png)
![2017-09-11 05_45_07-database cleaner - opera](https://user-images.githubusercontent.com/7478287/30257768-94eb648c-96b4-11e7-8469-b59763d06f36.png)

it's the same for ```u_rt_view```:
![2017-09-11 05_52_59-localhost_8080 _ localhost _ qi_phpbb321 _ phpmyadmin 4 5 4 1 - opera](https://user-images.githubusercontent.com/7478287/30257947-af2a52d0-96b5-11e7-97dc-60f92f3b9677.png)
![2017-09-11 05_53_20-database cleaner - opera](https://user-images.githubusercontent.com/7478287/30257946-af28d3d8-96b5-11e7-9662-f7bb9fec8073.png)

**Comment by avandenberghe** [comment]
this was a bug in the 2.0.6 migration.

**Comment by Galixte** [comment]
@Sajaki you missed ```u_rt_view``` in your commit: https://github.com/Sajaki/RecentTopics/commit/c0c64db5013d3c1335af85b8331dd8ec17ea6794 (see my previous post from the half, the 2nd part: “it's the same…”).

**Comment by avandenberghe** [comment]
hi Galixte, this is fixed now.
