### ISSUE TITLE
Problem with page selection

### ISSUE THREAD

**Issue by Next-rus** [Sajaki/RecentTopics#65]
phpbb 3.2.1
recenttopics 2.2.3

I have a problem with page selection.
For example. I had chosen 3rd page (in address bar: /index.php?recent_topics_start=10), but displayed 2nd page. When I had chosen 4th page (in address bar: /index.php?recent_topics_start=15), then displayed 3rd page. Etc.

**Comment by Galixte** [comment]
Duplicate of: https://github.com/Sajaki/RecentTopics/commit/52867dc9dbfc45ee07eb2c2cbe11eb32d3be102d#commitcomment-24421935

**Comment by avandenberghe** [comment]
solved in 2.2.4
