### ISSUE TITLE
Index body forumlist body after

### ISSUE THREAD

**Issue by Galixte** [Sajaki/RecentTopics#66]
Hi @Sajaki,

currently this file: https://github.com/Sajaki/RecentTopics/blob/develop32/styles/prosilver/event/index_body_forumlist_body_after.html is placed in the folder: ```./Sajaki/RecentTopics/styles/prosilver/event/index_body_forumlist_body_after.html```.

Why this file isn’t at this path: ```./Sajaki/RecentTopics/styles/prosilver/template/event/index_body_forumlist_body_after.html```?

**Comment by avandenberghe** [comment]
i removed it, it was a leftover file.
