### ISSUE TITLE
Show all pages doesnt work anymore with 2.2.4

### ISSUE THREAD

**Issue by bug-i** [Sajaki/RecentTopics#67]
Instead of displaing all pages now the number is limited to 100 (even with checked "show all pages") 
Could you please check that

Screenshot of ACP
![grafik](https://user-images.githubusercontent.com/29623218/30700500-0f46edec-9ee8-11e7-8483-f1967114561a.png)

Screenshot of Recent Topic at mainpage:
![grafik](https://user-images.githubusercontent.com/29623218/30700528-1b1b89f2-9ee8-11e7-970f-7eb0f4630e3e.png)

**Comment by avandenberghe** [comment]
hello, that's the case since 2.2.2, and by design. 100 pages should be enough.

**Comment by bug-i** [comment]
Nope. Its not. And it doesnt make sense.
Showing all pages suggests showing ALL pages and not only 100.

Why limiting to 100 for ALL pages when you can limit the number to 999 for showing a limited number. 

Why am I insisting on really showing all pages? So you can easily jump to the oldest topics in your board and read what people wrote long time ago. 

If there is not technical reason behind that then you should disable the limitation to 100 for showing all pages. (and it worked great without limitation in a previous version)

**Comment by Galixte** [comment]
@bug-i you have to increase this value, here: https://github.com/Sajaki/RecentTopics/blob/develop32/core/recenttopics.php#L225 to display more pages.

@Sajaki i don’t need about more pages, but I’m agree with bug-i, if the option says ALL it should be in accordance with the description. ;)

**Comment by avandenberghe** [comment]
any overflow pagelink should now just fetch the last page. this works in unread or all topics mode.

**Comment by Galixte** [comment]
Thanks a lot!

**Comment by bug-i** [comment]
Argh. Doesnt work in the latest release to fetch the last page
