### ISSUE TITLE
Not possible to click on large icon to get to the newest post

### ISSUE THREAD

**Issue by vassilisimon** [Sajaki/RecentTopics#73]
### Expected Behavior
It would be handy, if the large icon would be clickable, so that you get to the newest post.
http://www.financialwisdomforum.org/wp/wp-content/uploads/2015/02/topic-list-3.1.png

### Actual Behavior
Nothing happens.

### Steps to Reproduce the Problem

  1. Create new post with acc. A
  1. Refresh forum with acc. B
  1. Try to click on large icon with acc. B

### Specifications

  - phpbb version: 3.2.1
  - recenttopics version: 2.2.5

Thanks.

**Comment by Electrix** [comment]
This is connected to template class bug (classname was changed in prosilver 3.2.1). Pull request #72 fixes this issue for both "topbottom" and "side" templates.

**Comment by Galixte** [comment]
Maybe it can be closed. ;)

**Comment by avandenberghe** [comment]
Resolved: the extension has been renamed to recenttopicsav in 3.0.0.
