### ISSUE TITLE
Feature Request: user definable number of recent topics per page

### ISSUE THREAD

**Issue by bug-i** [Sajaki/RecentTopics#77]
Don't know if I did submit this request already, in that case: sorry for double opening this topic.

As some options are already user definable, I would like to have the number of recent topics User definable too. I have several discussions at my board. Some user like a lower number, some user like a higher number. Making this definable in the ucp would solve this.
Btw. Thanks for making recent topics working with collapsible categories.

**Comment by bug-i** [comment]
To make that clear: I am speaking of the number per page, not the total number of pages or topics.

**Comment by avandenberghe** [comment]
this should now be done.

**Comment by bug-i** [comment]
Awesome! Thanks for implementation. Can I already download the branch from github for testing, or do I have to wait for the final release?
