### ISSUE TITLE
Mistake in styles/all/template/event/nickvergessen_newspage_title_after.html

### ISSUE THREAD

**Issue by panteror** [Sajaki/RecentTopics#78]
Hi,

Just a mistake in RecentTopics/styles/all/template/event/nickvergessen_newspage_title_after.html

Line 6 {% INCLUDE 'recent_topics_bodybottom.html' %}

Replace by
{% INCLUDE 'recent_topics_body_topbottom.html' %}

It will be good if you can update newspage extension to 3.2, it seems working but no more support by the author.
here github and forum page
https://github.com/nickv-phpbb/phpbb-ext-newspage
https://www.phpbb.com/customise/db/extension/nickvergessen_newspage/

Thanks for your work

**Comment by avandenberghe** [comment]
I haven't really looked into fixing compatibility with NV Newspage since it's still only 3.1 compatible, but i think i may work on making it work on 3.2 since the author isn't. Once that's done we can revisit this issue.

**Comment by panteror** [comment]
Hi,
ok thanks, it will be awesome if you take time to update NV newspage for 3.2.

**Comment by avandenberghe** [comment]
reopen to keep track

**Comment by panteror** [comment]
ok, if you need tester, i can help.

**Comment by panteror** [comment]
Hi,
Do you start looking to update newspage ?
I think you're speaking french right ?
Thanks

**Comment by panteror** [comment]
Hi,
Sajaki, any progress to update newspage ?
Thanks
