### ISSUE TITLE
Feature/Support Request: embolden forum title in bread crumb of recent post entry

### ISSUE THREAD

**Issue by agg2** [Sajaki/RecentTopics#81]
I need to embolden (i.e. `<b></b>`, `<strong></strong>`, `font-weight: bold`) the forum title in the breadcrumb of the recent post entry.  Can you please advise me exactly where (which file and code line) to place the code that will allow me to embolden the forum title in the bread crumb?  Please note I am php-illiterate; I only know html and CSS.  But if you kindly suggest the line of code and where to put it, that I can manage.  Thank you.

e.g.

> Iterations » CIV 3 » Other Forums » Gameplay Help

becomes

> Iterations » **CIV 3** » Other Forums » Gameplay Help

### Expected Behavior

N/A

### Actual Behavior

N/A

### Steps to Reproduce the Problem

N/A

### Specifications

  - phpbb version: 3.2.1
  - recenttopics version: 2.2.5

**Comment by avandenberghe** [comment]
hi, 

it depends on the position. 

Open /styles/all/template/recent_topics_body_topbottom.html

Find and delete 

```{% for parent_forums in recent_topics.parent_forums %}<a href="{{ parent_forums.U_VIEW_FORUM }}">{{ parent_forums.FORUM_NAME }}</a> &raquo; {% endfor %}<a href="{{ recent_topics.U_VIEW_FORUM }}">{{ recent_topics.FORUM_NAME }}</a>{% endif %}```

Add this for emboldening the first parent forum

```
{% for parent_forums in recent_topics.parent_forums %}
{% if loop.first  %} <b> {% endif %}
<a href="{{ parent_forums.U_VIEW_FORUM }}">{{ parent_forums.FORUM_NAME }}</a> &raquo;
{% if loop.first %} </b> {% endif %}
{% endfor %}
<a href="{{ recent_topics.U_VIEW_FORUM }}">{{ recent_topics.FORUM_NAME }}</a>{% endif %}
```

Add this for emboldening the last  parent forum.

```
{% for parent_forums in recent_topics.parent_forums %}
{% if loop.last  %} <b> {% endif %}
<a href="{{ parent_forums.U_VIEW_FORUM }}">{{ parent_forums.FORUM_NAME }}</a> &raquo;
{% if loop.last %} </b> {% endif %}
{% endfor %}
<a href="{{ recent_topics.U_VIEW_FORUM }}">{{ recent_topics.FORUM_NAME }}</a>{% endif %}
```

Add this for emboldening only the last forum
```
{% for parent_forums in recent_topics.parent_forums %}
<a href="{{ parent_forums.U_VIEW_FORUM }}">{{ parent_forums.FORUM_NAME }}</a> &raquo;
{% endfor %}
<b><a href="{{ recent_topics.U_VIEW_FORUM }}">{{ recent_topics.FORUM_NAME }}</a> </b> {% endif %}
```

**Comment by agg2** [comment]
Thank you for your reply.  What about for the first forum (perhaps if you could generalise your answer to the _**nth**_ forum)?  I was after something to this effect:

Iterations » **CIV 3** » Other Forums » Gameplay Help
CATEGORY >> **first forum** >> second forum >> last forum

Thank you.

**Comment by agg2** [comment]
I've also had little luck generalising the style to something a bit more sophisticated than just <b></b>.

For example, I wanted `<span style="background: #222; color: white> &nbsp; <a>nth forum</a> &nbsp;</span>`.  Any tips here?  Thank you.

**Comment by avandenberghe** [comment]
hi, 
in the html i can't distinguish between categories and parent forums. they're all considered as parents. 

So supposing that your first parent forum is a category, and the second is the first forum, you could do this to always bold the "first" forum in the breadcrumb.  

```
{% for parent_forums in recent_topics.parent_forums %}
{% if loop.index == 2 %} <b> {% endif %}
<a href="{{ parent_forums.U_VIEW_FORUM }}">{{ parent_forums.FORUM_NAME }}</a> &raquo;
{% if loop.index == 2 %} </b> {% endif %}
{% endfor %}
<a href="{{ recent_topics.U_VIEW_FORUM }}">{{ recent_topics.FORUM_NAME }}</a>{% endif %}
```

**Comment by agg2** [comment]
In that case, how would I select the forum by _name_?  That would also allow me to style different forums differently at the same level.

So I want to say in code, if the forum name = "Foo1", style like this, if the forum name = "Foo2" style like that, and so forth.

**Comment by Leinad4Mind** [comment]
you need to make an if statement

if parent_forums.FORUM_NAME == foo then do something
