### ISSUE TITLE
Where are the settings?

### ISSUE THREAD

**Issue by Bizarrus** [Sajaki/RecentTopics#84]
### Expected Behavior
A settings page on `Extension`  tab on `ACP`

### Actual Behavior
not shown

### Specifications

  - phpbb version: latest (3.2.1)
  - recenttopics version: latest from GitHub (2.2.6), same tested with 2.2.5 from official thread (https://www.phpbb.com/customise/db/extension/recent_topics_2)

**Comment by avandenberghe** [comment]
Extensions tab -> Recent Topics
