### ISSUE TITLE
Recent topic displays double on index page

### ISSUE THREAD

**Issue by benchess** [Sajaki/RecentTopics#87]
- phpbb version: 3.2
  - recenttopics version:

I use the latest version 3.2 with recent topic compatibility pack.
recent topic showing a compatible topic and another incompatible topic in frontend index.

how do i remove the second recent topic list

**Comment by avandenberghe** [comment]
please don't use the recent topics compatibility pack provided here https://comboot.io/compatibility/, it's out of date. 
remove the folder /ext/paybas/recenttopics/styles/comboot

**Comment by avandenberghe** [comment]
please seel #88
