### ISSUE TITLE
Settings are not shown anywhere

### ISSUE THREAD

**Issue by forumcv** [Sajaki/RecentTopics#89]
### Expected Behavior
1. Settings for "Recent Topics" extensions should be on "Extensions" tab in ACP
2. Settings should be shown in UCP - Profile - Board Preferences - Edit Global Settings(or Edit Display Options, can't remember exactly)

### Actual Behavior
Settings are not shown anywhere

### Steps to Reproduce the Problem
  1. Installed extension
  2. Enable it in ACP - Customize - Manage Extensions
  3. Clear cache 
  4. Go to ACP - Extensions
  5. Go to UCP - Profile - Board Preferences - Edit Global Settings(or Edit Display Options, can't remember exactly)

### Additional info:
Previously we had 2.2.5 recent topics and there wasn't settings in ACP, but was in UCP. On 2.2.6 they disappeared even from UCP.

### Specifications

  - phpbb version: 3.2.1
  - recenttopics version: 2.2.6 (updated from 2.2.5)

**Comment by avandenberghe** [comment]
Settings should be in the extensions tab. 
If not, please disable extension and then remove data. then reinstall.

![capture](https://user-images.githubusercontent.com/226730/35289482-c48cfbca-0067-11e8-8f3c-ee18befe628e.JPG)

**Comment by forumcv** [comment]
I know where it should be. But unfortunately they are not there. I've tried to reinstall extension for a couple of times with different methods. I beleive there is some problem while migrating from phpbb 3.1.3(with Recent Topics for that version) to 3.2.1. Maybe some conflicts in database
But it's just a suggession and I don't know that to do.

**Comment by avandenberghe** [comment]
> Previously we had 2.2.5 recent topics and there wasn't settings in ACP, but was in UCP. On 2.2.6 they disappeared even from UCP.

The only migration file that impacts the ACP is v2.0.0.

Nothing special changed between 2.2.5 & 6 except a change from native phpBB template syntax to Twig Syntax, and support for Collapsable Categories.
