### ISSUE TITLE
Additional bug(s) within group rights

### ISSUE THREAD

**Issue by bug-i** [Sajaki/RecentTopics#94]
As commented in #93 (I couldnt reopen the issue):

I probalbly found one/two minor bugs:
The option in UCP "can change setting of number of recent topics to show per page." is only shown, if group rights "can enable or disable Displaying Recent Topics." are set to "yes".
If "can enable or disable Displaying Recent Topics." is set to "no" - "can change setting of number of recent topics to show per page." is not shown. No matter if I set it to yes or no.

Another question: Whats the purpose behind the last option/group right "Recent Topics: can view Recent topics." - if I enable that in the group rights it doesnt change anything at all. No additional option in UCP is available, and recent topics is shown. No matter if I set it to yes or no. Kind of duplicate to the first option "can enable or disable Displaying Recent Topics" which works perfect.

**Comment by bug-i** [comment]
And a third bug: An admin cant change the new UCP-options for single users. I if log in as admin and administrate single users all the new UCP-option are not shown.  In my own UCP I can see the options.
I can provide screenshots, if it is not clear what I mean.

**Comment by avandenberghe** [comment]
Cannot reproduce.
