### ISSUE TITLE
Topics icons written over

### ISSUE THREAD

**Issue by Monsieurbaron** [Sajaki/RecentTopics#96]
Hello, 

I've installed latest version of this extension on my board. This one is in phpBB 3.1. 
Topics icons are at the wrong place and written over. I can't find where to fix this or figure how. 
So I removed every topics icons from ACP but they're still showing up in recent topics list. 
Any clue about all of this ? 

Thx a lot !

**Comment by avandenberghe** [comment]
>  This one is in phpBB 3.1.


the latest version for phpBB 3.1 is v2.1.4
