### ISSUE TITLE
Request: How to have Recent Topics more then once?

### ISSUE THREAD

**Issue by aldaw** [Sajaki/RecentTopics#99]
Hello,

I am looking to doublicate Recent Topics, one for 'News', and one for 'Global new posts(excluding News Forum)'.
I am sure this should be kind of do able very easy in a dirty way i guess.

I thought like as example really dirty, just install the add-on 2 Times, but i would have tried if I would now how.

By the way, amazing add-on amazing community! 
Love

Original Post: https://www.phpbb.com/customise/db/extension/recent_topics_2/support/topic/191031

**Comment by avandenberghe** [comment]
Recent topics has a custom page, you can acess it via /app.php/rt. 

Other than that, the embed code below is put in the event index_body_markforums_after.html

```
<div id="recenttopicstop">
{% INCLUDE 'recent_topics_body_topbottom.html' %}
</div>
```
it's not currently possible to have different content depending on the block position.
